trigger: none

pool:
  vmImage: 'ubuntu-latest'

steps:
- script: |
    sudo apt install bc
    git clone https://github.com/myst33d/AnyKernel3 -b cactus ak3
    sudo echo "deb http://ftp.debian.org/debian experimental main contrib non-free" >> /etc/apt/source.list
    sudo apt update
    sudo apt install gcc-10-arm-linux-gnueabihf
    make O=out CROSS_COMPILE=arm-linux-gnueabihf- SUBARCH=arm ARCH=arm -j$(nproc --all) cactus_defconfig
    make O=out CROSS_COMPILE=arm-linux-gnueabihf- SUBARCH=arm ARCH=arm -j$(nproc --all)
    cp out/arch/arm/boot/zImage-dtb ak3/zImage-dtb
    cd ak3
    zip -r9 cherrykernel-cactus-$(Build.SourceBranchName).zip *
    cp cherrykernel-cactus-$(Build.SourceBranchName).zip ../cherrykernel-cactus-$(Build.SourceBranchName).zip
  displayName: 'Compile Cherry Kernel for Redmi 6A $(Build.SourceBranchName)'
- task: CopyFiles@2
  inputs:
    contents: 'cherrykernel-cactus-$(Build.SourceBranchName).zip'
    targetFolder: $(Build.ArtifactStagingDirectory)
  displayName: 'Copy kernel to artifacts folder'
- task: PublishBuildArtifacts@1
  inputs:
    pathToPublish: $(Build.ArtifactStagingDirectory)
    artifactName: cherrykernel-cactus-$(Build.SourceBranchName)
  displayName: 'Upload kernel'