name: Kernel

on: push

jobs:
  build:
    name: Cereus;
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v1
    - name: Build Kernel
      run: |
        chmod a+x ./cereus.sh
        ./cereus.sh
      shell: bash
      env:
        TELEGRAM_CHAT: ${{ secrets.TELEGRAM_CHAT }} 
        TELEGRAM_TOKEN: ${{ secrets.TELEGRAM_TOKEN }} 
        GITOKEN: ${{ secrets.GITOKEN }}
